# The most powerful quantum algorithm

*Mathematical analysis is as extensive as nature itself; it defines all perceptible relations, measures times, spaces, forces, temperatures: this difficult science is formed slowly, but it preserves every principle which it has once acquired; it grows and strengthens itself incessantly in the midst of the many variations and errors of the human mind. Its chief attribute is clearness; it has no marks to express confused notations. It brings together phenomena the most diverse and discovers the hidden analogies which unite them.* - Joseph Fourier, The Analytical Theory of Heat (1822) 

This chapter is atypical of the rest of this textbook. Here a rather lengthy historical introduction is given in an attempt to convey the power of what could be considered the most powerful quantum algorithm. It is what drives Shor's algorithm along with every other quantum algorithm with exponential scaling. 

## Signal processing 

*The transformation of signals into a sum of small, overlapping waves offers a new method for analyzing, storing and transmitting information* - Gilbert Slang 1994


Waves surround us. Light travels from the sun to our eyes and sound travels from vibrating objects to our ears and those two waves comprise much of our experience of reality. For both light and sound, what we are sensitive to is small changes of intensity, the power per unit area, that the complex network of our sense organs and brain are able to process and interpret as what we see and hear. In engineering, signal processing is extremely important in telecommunications and in physics there are insights we can gain about the nature of solids (condensed matter physics) by performing a similar analysis. In the latter two cases, the mathematics we use to accomplish these tasks is described by various Fourier Transforms. 

In 1822, French mathematician, Joseph Fourier proposed a method for 

## Turning the Tide

Until the invention of the airplane in 1903, the world could only be circumvented by ship. Sailing ships depended on the winds and the waves to move. Being able to effectively predict the weather & tides became an essential tool for merchant fleets and navies. 

There are two complete cycles of high-low tides each day. This is caused by the gravitational pull of the moon & the sun. At different times of year, the difference in the distances between the Earth, moon & sun, along with differences in latitude, cause the times of the tides to drift. 

In 1867, William Thompson, better known as Lord Kelvin, realised that the Fourier transform could be used to represent the height of the tides as a sum of sinusoids. 



- William Thompson's work on analogue computing 
- The use of FT's to predict tides & it's effect in WW2

[Manhattan example of predicting the tides](https://www.whydomath.org/node/hearing/fourierHarmonicAnalysis.html)

## The most important (classical) algorithm

- Introduce the FFT 
- 


> TODO: Veritasium Video 

## A change of perspective 

- The use of FTs to transform between time/frequency
    - Wavelength & wave-vectors (MRI applications)


## Discrete vs continuous Fourier Transforms 


- The significance of choosing between a discrete or continuous FT

## The quantum mechanical treatment

In quantum mechanics, the quantum Fourier transform can be used to convert between position & momentum representations of a wavefunction. 

Transforming from the time domain to the frequency domain, from position-space to momentum/wavevector-space is a powerful tool in physics.

>> Define the continuous semi-classical QFT 

## Quantum phase estimation

Quantum information allows another application of the QFT to be defined. 

The standard (computational) basis in which qubits are measured is the z-basis. That is to say we measure all the qubits by projecting them onto the Z-axis of the Bloch Sphere. All our qubits will end up as $\ket{0}$ or $\ket{1}$. Repeated measurements can be used to reveal the probability amplitudes for the $\ket{0}$ or $\ket{1}$ states. This is state tomography. However doing this does not reveal anything about the phase of the qubits. In order to extract this information from a measurement, we ust first change our basis. 

The Fourier basis is a bit like describing the state $\ket{\psi}$ using the polar coordinate $\phi$. Whereas the Z-basis has measurement outcomes in binary, for example  

$$ \ket{0010} = \ket{2} $$

The Fourier basis has measurement outcomes corresponding to the phase angle around the Bloch Sphere. To better understand what this means, it is convenient to consider phase in more detail. 




>> Uncertainty in probability vs phase from quantum measurement 


## Constructive interference: The power behind Shor's Algorithm

The QFT can be considered similar to putting a series of slits in front of a source of light & observing the resultant pattern on some distant screen. 

Instead of a classical beam of light, as described by Maxwell's equations, a source of quantised light, photons, would be better. For quantum computing, we only require that the physical system be described entirely quantum mechanically. 


## A new limit of machine precision 

[Qiskit Lab 5: Accuracy of Quantum Phase Estimation](https://learn.qiskit.org/course/ch-labs/lab-5-accuracy-of-quantum-phase-estimation)

Digital computers are fundamentally limited in the precision they can achieve. Floating point numbers carry a finite number of bits. 32 bit for single precision, 64 for double precision. What this means is that every number stored on every computer is stored to a finite number of decimal points. Even for analogue computers, there is some arbitrary degree to which the precision of a given value can be stored. 

Perhaps one of the most remarkable differences between quantum & classical information is phase. 

Phases can be stored classically using complex data structures: a complex number is merely 2 real numbers where one is the real component & the other is the imaginary component. The difference with quantum states is that the phase is realised physically. In that sense it is fundamentally analogue. 

*$F$* is defined with some limit:

$$ \textbf{F} = QFT^\dagger \frac{1}{\sqrt{N}}\sum_{j,k = 0}^{N-1} \omega^{-jk}\ket{k}\bra{j}$$

With $ N = 2^n$ ($n$ being the number of logical qubits) & $\omega = e^{i2\pi/N}$

Since we know that $\omega$ is quantised, there is a limit to which the phase can be specified. Therefore, for some arbitrary phase angle $\phi$, and for a given number of qubits, there is a limit to the accuracy this phase can be estimated (using QPE). The maximum error to which this phase can be measured is given by the angular distance $\Delta$

$$ \Delta = | \phi - 2\pi jk/N | $$

In the best case, $\phi = 0 $, so simply picking $ j = k = 0 $ allows $\Delta = | 0 - 0 | = 0 $. In that case, there is no phase and therefore no error ($\Delta_{min} = 0$). 

In the worst case, $\phi_{worst}$ falls between two of the roots of unity: $\phi_{worst} = 2\pi jk/2N$. This maximises the angular distance $\Delta$


$$ \Delta_{max} = | 2\pi jk/2N - 2\pi jk/N | $$

Since we can always rotate the Bloch sphere by some integer number of $ 2\pi/N $ without changing $ \Delta $, we can simplify this to take $j = k = 1$

$$ \Delta_{max} = 2\pi \left| \frac{1}{2N} - \frac{1}{N} \right| $$

Multiplying by $-1$ makes this positive

$$ \Delta_{max} = 2\pi\left( \frac{1}{N} - \frac{1}{2N} \right) $$
$$ = 2\pi\left(  \frac{ 2 -1}{2N}   \right) = \frac{\pi}{N} $$

Leaving us with the worst case error 


$$ \Delta_{max} = \frac{\pi}{N} $$

Assuming an ideal (full-scale fault-tolerant) quantum computer, the (phase) limit of machine precision can be given by:
$$
\lim_{n \rightarrow \infty} \Delta_{max} = \frac{\pi}{2^n} \rightarrow 0
$$

At first glance, it would seem that it is as simple as setting having as many qubits as possible such that $N = 2^n$ goes to infinity and $\Delta_{max}$ goes to zero. Alas, there are a few more considerations:

- Connectivity: All-to-all connectivity is required by $F$. This can be overcome with SWAP gates at some overhead that scales with $n$ depending on local (logical) qubit connectivity.
- Phase control: Controlled $R_z$ gates with at least $2\pi/N$ precision. Effectively this defines a limit on the maximum phase noise that can be tolerated by 2-qubit gates. Practically speaking, this demands effective quantum error correcting codes.
- Coherence times: For any given $n$, $F$ requires $O(n^3)$ circuit layers. Thus the minimum depth of the circuit also scales with $O(n^3)$. Each layer of the circuit requires some time to be processed. Thus it is necessary to maintain a coherent phase for at least the time taken to complete the QPE algorithm. 
- SPAM: State Preparation And Measurement. The quantum circuit has to start from the fiduciary state $\ket{0}^{\otimes n}$, prepare the phase corresponding to $\phi_{worst}$, carry out QPE and them perform a measurement in the computational basis. Any error in preparing the state or measuring it will in turn raise the error beyond $\Delta_{max}$.

At this point it is worth pointing out that there is no major consideration for speed. Whether QPE is implemented very quickly or extremely slowly, all other things being equal, it doesn't affect $\Delta $. Intuitively this makes sense. Precision does not require speed.

### Defining a phase figure of merit 

$\Delta_{max}$ is useful as a measure of error, but for a more holistic description of the power of a quantum computer, a better figure of merit is needed. 

Fidelity is very important in everyday life. Fidelity tells you how much you can trust a quantum state, or human being. It can be defined using statevectors as

$$
F(\psi,\phi) = |\braket{\phi|\psi}|^2
$$

This measure of fidelity assumes the quantum states $\ket{\phi}$ \& $\ket{\psi}$ are pure (there is no entanglement in either of them seperately).The inner product corresponds to how well these statevectors overlap with each other. In turn, this number between 0 \& 1 indicates the probability of measuring $\ket{\phi}$ if given the state $\ket{\psi}$ (or vice-versa).

In the general case, where either or both of the quantum states may be entangled, the density matrix is used instead.

In [33]:
import numpy as np
pi = np.pi
# Code to display the QFT as a matrix

def display_QFT(n,sigfig = 8):
    """
    Function that displays the matrix form of the QFT
    """

    N = int(2**n)
    omega = np.exp(1j * 2 *pi/N )
    F_mat = np.zeros([N,N],dtype='complex_')


    for j in range(N):
        for k in range(N):
            F_mat[j,k] = np.round(omega**(j*k),sigfig)
    print(F_mat)

def indices_QFT(n):
    """
    Function that displays the indices of the powers of omega to which the matrix elements of F are raised
    """
    N = int(2**n)
    omega = np.exp(1j * 2 *pi/N )
    F_ind = np.zeros([N,N])


    for j in range(N):
        for k in range(N):
            F_ind[j,k] = (j*k)%N
    print(F_ind)

In [35]:
display_QFT(3,1)
indices_QFT(3)

[[ 1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j
   1. +0.j ]
 [ 1. +0.j   0.7+0.7j  0. +1.j  -0.7+0.7j -1. +0.j  -0.7-0.7j -0. -1.j
   0.7-0.7j]
 [ 1. +0.j   0. +1.j  -1. +0.j  -0. -1.j   1. +0.j   0. +1.j  -1. +0.j
  -0. -1.j ]
 [ 1. +0.j  -0.7+0.7j -0. -1.j   0.7+0.7j -1. +0.j   0.7-0.7j  0. +1.j
  -0.7-0.7j]
 [ 1. +0.j  -1. +0.j   1. +0.j  -1. +0.j   1. +0.j  -1. +0.j   1. +0.j
  -1. +0.j ]
 [ 1. +0.j  -0.7-0.7j  0. +1.j   0.7-0.7j -1. +0.j   0.7+0.7j -0. -1.j
  -0.7+0.7j]
 [ 1. +0.j  -0. -1.j  -1. +0.j   0. +1.j   1. +0.j  -0. -1.j  -1. +0.j
   0. +1.j ]
 [ 1. +0.j   0.7-0.7j -0. -1.j  -0.7-0.7j -1. +0.j  -0.7+0.7j  0. +1.j
   0.7+0.7j]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 2. 4. 6. 0. 2. 4. 6.]
 [0. 3. 6. 1. 4. 7. 2. 5.]
 [0. 4. 0. 4. 0. 4. 0. 4.]
 [0. 5. 2. 7. 4. 1. 6. 3.]
 [0. 6. 4. 2. 0. 6. 4. 2.]
 [0. 7. 6. 5. 4. 3. 2. 1.]]
