## The most powerful quantum algorithm

*Mathematical analysis is as extensive as nature itself; it defines all perceptible relations, measures times, spaces, forces, temperatures: this difficult science is formed slowly, but it preserves every principle which it has once acquired; it grows and strengthens itself incessantly in the midst of the many variations and errors of the human mind. Its chief attribute is clearness; it has no marks to express confused notations. It brings together phenomena the most diverse and discovers the hidden analogies which unite them.* - Joseph Fourier, The Analytical Theory of Heat (1822) 

This chapter is atypical of the rest of this textbook. Here a rather lengthy historical introduction is given in an attempt to convey the power of what could be considered the most powerful quantum algorithm. It is what drives Shor's algorithm along with every other quantum algorithm with exponential scaling. 

## Signal processing 

*The transformation of signals into a sum of small, overlapping waves offers a new method for analyzing, storing and transmitting information* - Gilbert Slang 1994


Waves surround us. Light travels from the sun to our eyes and sound travels from vibrating objects to our ears and those two waves comprise much of our experience of reality. For both light and sound, what we are sensitive to is small changes of intensity, the power per unit area, that the complex network of our sense organs and brain are able to process and interpret as what we see and hear. In engineering, signal processing is extremely important in telecommunications and in physics there are insights we can gain about the nature of solids (condensed matter physics) by performing a similar analysis. In the latter two cases, the mathematics we use to accomplish these tasks is described by various Fourier Transforms. 

In 1822, French mathematician, Joseph Fourier proposed a method for 

## Turning the Tide


- William Thompson's work on analogue computing 
- The use of FT's to predict tides & it's effect in WW2



## The most important (classical) algorithm

- Introduce the FFT 
- 


> TODO: Veritasium Video 

## A change of perspective 

- The use of FTs to transform between time/frequency
    - Wavelength & wave-vectors (MRI applications)


## Discrete vs continuous Fourier Transforms 


- The significance of choosing between a discrete or continuous FT

## The quantum mechanical treatment

In quantum mechanics, the quantum Fourier transform can be used to convert between position & momentum representations of a wavefunction. 


## Quantum phase estimation


## Constructive interference: The power behind Shor's Algorithm

The QFT can be considered similar to putting a series of slits in front of a source of light & observing the resultant pattern on some distant screen. 

Instead of a classical beam of light, as described by Maxwell's equations, a source of quantised light, photons, would be better. For quantum computing, we only require that the physical system be described entirely quantum mechanically. 


## The quantum limit of machine precision 

Digital computers are fundamentally limited in the precision they can achieve. Floating point numbers carry a finite number of bits. 32 bit for single precision, 64 for double precision. What this means is that every number stored on every computer is stored to a finite number of decimal points. Even for analogue computers, there is some arbitrary degree to which the precision of a given value can be stored. 

Perhaps one of the most remarkable differences between quantum & classical information is phase. 

Phases can be stored classically using complex data structures: a complex number is merely 2 real numbers where one is the real component & the other is the imaginary component. The difference with quantum states is that the phase is realised physically. In that sense it is fundamentally analogue. 

$F$ is defined with some limit:

$$ F = \frac{1}{\sqrt{N}}\sum_{j,k = 0}^{N-1} \omega^{jk}\ket{k}\bra{j}$$

With $ N = 2^n$ ($n$ being the number of logical qubits) & $\omega = e^{i2\pi/N}$

Since we know that $\omega$ is quantised, there is a limit to which the phase can be specified. Therefore, for some arbitrary phase angle $\phi$, and for a given number of qubits, there is a limit to the accuracy this phase can be estimated (using QPE). The maximum error to which this phase can be measured is given by 

$$
\Delta = | \phi - 2\pi jk/N |
$$



In [33]:
import numpy as np
pi = np.pi
# Code to display the QFT as a matrix

def display_QFT(n,sigfig = 8):
    """
    Function that displays the matrix form of the QFT
    """

    N = int(2**n)
    omega = np.exp(1j * 2 *pi/N )
    F_mat = np.zeros([N,N],dtype='complex_')


    for j in range(N):
        for k in range(N):
            F_mat[j,k] = np.round(omega**(j*k),sigfig)
    print(F_mat)

def indices_QFT(n):
    """
    Function that displays the indices of the powers of omega to which the matrix elements of F are raised
    """
    N = int(2**n)
    omega = np.exp(1j * 2 *pi/N )
    F_ind = np.zeros([N,N])


    for j in range(N):
        for k in range(N):
            F_ind[j,k] = (j*k)%N
    print(F_ind)

In [35]:
display_QFT(3,1)
indices_QFT(3)

[[ 1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j   1. +0.j
   1. +0.j ]
 [ 1. +0.j   0.7+0.7j  0. +1.j  -0.7+0.7j -1. +0.j  -0.7-0.7j -0. -1.j
   0.7-0.7j]
 [ 1. +0.j   0. +1.j  -1. +0.j  -0. -1.j   1. +0.j   0. +1.j  -1. +0.j
  -0. -1.j ]
 [ 1. +0.j  -0.7+0.7j -0. -1.j   0.7+0.7j -1. +0.j   0.7-0.7j  0. +1.j
  -0.7-0.7j]
 [ 1. +0.j  -1. +0.j   1. +0.j  -1. +0.j   1. +0.j  -1. +0.j   1. +0.j
  -1. +0.j ]
 [ 1. +0.j  -0.7-0.7j  0. +1.j   0.7-0.7j -1. +0.j   0.7+0.7j -0. -1.j
  -0.7+0.7j]
 [ 1. +0.j  -0. -1.j  -1. +0.j   0. +1.j   1. +0.j  -0. -1.j  -1. +0.j
   0. +1.j ]
 [ 1. +0.j   0.7-0.7j -0. -1.j  -0.7-0.7j -1. +0.j  -0.7+0.7j  0. +1.j
   0.7+0.7j]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 2. 4. 6. 0. 2. 4. 6.]
 [0. 3. 6. 1. 4. 7. 2. 5.]
 [0. 4. 0. 4. 0. 4. 0. 4.]
 [0. 5. 2. 7. 4. 1. 6. 3.]
 [0. 6. 4. 2. 0. 6. 4. 2.]
 [0. 7. 6. 5. 4. 3. 2. 1.]]
